name: deploy-auth

on:
  push:
    branches: ["main"]
    paths: ["infra/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Connect to digitalocean k8s
        run: doctl kubernetes cluster kubeconfig save $DIGITALOCEAN_CLUSTER_ID
        env:
          DIGITALOCEAN_CLUSTER_ID: ${{ secrets.DIGITALOCEAN_CLUSTER_ID }}
      - name: Deploy infra/k8s
        run: kubectl apply -f infra/k8s
